title: Wenzheng Cheng
name: Wenzheng Cheng
description: "Surgical Computer Vision · Multimodal Learning · Digital Twins · Robot Learning"
url: "https://wilsoncheng561.github.io"
baseurl: ""

# Theme
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# Build
plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Jekyll will process these folders
include: ["_pages", "_includes", "assets"]

# Collections (keep minimal; you can add later)
collections:
  posts:
    output: true

# Defaults: enable left author profile on pages & posts
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      classes: wide
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true

# Author card (left column)
author:
  name: "WENZHENG CHENG"          # 大写展示名字
  avatar: "/assets/avatar.jpg"
  bio: "M.S. Robotics @ JHU (LCSR). Surgical CV, Multimodal Learning, Digital Twins."
  location: "MD, USA"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:wcheng31@jh.edu"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=fGDg-S4AAAAJ"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/WilsonCheng561"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/wenzheng-cheng-3a827b327/?locale=en_US"
    - label: "WeChat (QR)"
      icon: "fas fa-comments"
      url: "/assets/wechat_qr.jpg"
    - label: "CV (PDF)"
      icon: "fas fa-file-pdf"
      url: "/assets/Wenzheng Cheng_Resume.pdf"

# Feed & sitemap
feed:
  path: feed.xml

# (Optional) SCSS override, if you后面想自定义样式
sass:
  style: compressed
